[[plugins]]
  package = "@netlify/plugin-inline-functions-env"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-run"
  [plugins.inputs]
    command = "npm run dev"
